import { ALL_CAMPAIGNS, INACTIVE_CAMPAIGNS, GET_CAMPAIGN, HUNTERS_CAMPAIGN } from './campaign';
import { ME, SIGN_IN } from './user';
import { HUNTER_COUPONS_IN_COMPANY, HUNTER_COUPONS_IN_CAMPAING } from './hunter';
import { COMPANY, OFFICES, HUNTERS_COMPANY } from './company';

export default {
  ME,
  SIGN_IN,
  ALL_CAMPAIGNS,
  INACTIVE_CAMPAIGNS,
  GET_CAMPAIGN,
  HUNTERS_CAMPAIGN,
  HUNTER_COUPONS_IN_COMPANY,
  HUNTER_COUPONS_IN_CAMPAING,
  COMPANY,
  OFFICES,
  HUNTERS_COMPANY,
}
